### ISSUE TITLE
Fix any warnings appearing in iOS 11

### ISSUE THREAD

**Issue by nevyn** [nevyn/SPStackedNav#3]
I'm sure there are some...

**Comment by JagCesar** [comment]
This seems like an easy one. I'll give it a shot :)

**Comment by nevyn** [comment]
And broken behavior due to iOS changes, which I'm sure there are also a bunch of :P

**Comment by nevyn** [comment]
This is now fixed <3 Filed the only ios11 behavior breakage I could find as #11 :)

Thanks for fixing @JagCesar!!!
